-- JobHunt database. Paste this whole file into Supabase → SQL Editor → New query → Run.
-- Every table is protected by row-level security: each signed-in user only ever sees their own rows.

create table if not exists public.profiles (
  user_id     uuid primary key default auth.uid() references auth.users on delete cascade,
  data        jsonb,
  cv_text     text default '',
  li_text     text default '',
  sources     jsonb default '{}'::jsonb,
  updated_at  timestamptz default now()
);

create table if not exists public.jobs (
  user_id          uuid not null default auth.uid() references auth.users on delete cascade,
  id               text not null,
  title            text, company text, company_url text, location text,
  posted_date      text, posted_text text, url text, apply_url text, logo text, salary text,
  description      text, seniority text, employment_type text, job_function text, industries text,
  applicants       text, poster_name text, poster_title text, poster_url text, query text,
  score            integer, match jsonb, tailor jsonb,
  hidden           boolean not null default false,
  first_seen       timestamptz default now(),
  updated_at       timestamptz default now(),
  primary key (user_id, id)
);

create table if not exists public.applications (
  id                bigint generated by default as identity primary key,
  user_id           uuid not null default auth.uid() references auth.users on delete cascade,
  job_id            text,
  title             text not null, company text not null, location text, url text, source text,
  status            text not null default 'wishlist',
  applied_date      text, salary text, priority integer default 2, cv_version text,
  next_action       text, next_action_date text, notes text,
  created_at        timestamptz default now(),
  updated_at        timestamptz default now()
);

create table if not exists public.contacts (
  id                bigint generated by default as identity primary key,
  user_id           uuid not null default auth.uid() references auth.users on delete cascade,
  application_id    bigint not null references public.applications on delete cascade,
  name text not null, role text, email text, linkedin text, phone text, notes text,
  last_contacted    text, next_contact_date text,
  created_at        timestamptz default now()
);

create table if not exists public.events (
  id                bigint generated by default as identity primary key,
  user_id           uuid not null default auth.uid() references auth.users on delete cascade,
  application_id    bigint not null references public.applications on delete cascade,
  date text not null, type text not null default 'note', summary text not null,
  created_at        timestamptz default now()
);

create index if not exists applications_user_idx on public.applications (user_id);
create index if not exists contacts_app_idx on public.contacts (application_id);
create index if not exists events_app_idx on public.events (application_id);
create index if not exists jobs_user_score_idx on public.jobs (user_id, score desc);

do $$
declare t text;
begin
  foreach t in array array['profiles', 'jobs', 'applications', 'contacts', 'events'] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists "own rows" on public.%I', t);
    execute format('create policy "own rows" on public.%I for all to authenticated
                    using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id)', t);
  end loop;
end $$;
